services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./seed-scripts:/docker-entrypoint-initdb.d  # Mount seed scripts
    networks:
      - local_network

  node:
    build: ../server    # path to the Dockerfile inside 'server/' if you're running compose from 'mysql-docker-setup'
    container_name: my_node_app
    ports:
      - "80:3000"       # map host port 80 → container port 3000
    environment:
      DB_HOST: mysql
      DB_USER: my_user
      DB_PASSWORD: my_password
      DB_NAME: my_database
    depends_on:
      - mysql
    networks:
      - local_network
      
volumes:
  mysql_data:

networks:
  local_network:
